---
# tasks file for hello
- name: Initiate include separated-task
  ansible.builtin.include_tasks:
    file: ansible/tasks/separated-task.yml
    apply:
      tags:
        - turnon
        - turnoff
